import { defineManifest } from '@crxjs/vite-plugin'

export default defineManifest({
  manifest_version: 3,
  name: 'AI Water Tracker',
  version: '1.0.0',
  description:
    'Tracks supported AI websites and estimates water consumption from visits, prompts, and active time.',
  permissions: ['storage', 'tabs'],
  host_permissions: [
    'https://chatgpt.com/*',
    'https://chat.openai.com/*',
    'https://openai.com/*',
    'https://sora.com/*',
    'https://gemini.google.com/*',
    'https://aistudio.google.com/*',
    'https://claude.ai/*',
    'https://www.perplexity.ai/*',
    'https://perplexity.ai/*',
    'https://meta.ai/*',
    'https://www.meta.ai/*',
    'https://ai.meta.com/*',
    'https://grok.com/*',
    'https://www.grok.com/*',
    'https://x.ai/*',
    'https://x.com/*',
    'https://www.x.com/*',
    'https://copilot.microsoft.com/*',
    'https://www.deepseek.com/*',
    'https://chat.deepseek.com/*',
  ],
  background: {
    service_worker: 'src/utils/background.ts',
    type: 'module',
  },
  action: {
    default_title: 'AI Water Tracker',
    default_popup: 'index.html',
  },
  content_scripts: [
    {
      matches: [
        'https://chatgpt.com/*',
        'https://chat.openai.com/*',
        'https://openai.com/*',
        'https://sora.com/*',
        'https://gemini.google.com/*',
        'https://aistudio.google.com/*',
        'https://claude.ai/*',
        'https://www.perplexity.ai/*',
        'https://perplexity.ai/*',
        'https://meta.ai/*',
        'https://www.meta.ai/*',
        'https://ai.meta.com/*',
        'https://grok.com/*',
        'https://www.grok.com/*',
        'https://x.ai/*',
        'https://x.com/*',
        'https://www.x.com/*',
        'https://copilot.microsoft.com/*',
        'https://www.deepseek.com/*',
        'https://chat.deepseek.com/*',
      ],
      js: ['src/utils/content.ts'],
      run_at: 'document_idle',
    },
  ],
})